### ISSUE TITLE
Not working in Android Studio 2.1.2

### ISSUE THREAD

**Issue by sha256** [dmytrodanylyk/folding-plugin#15]
As mentioned in #14, it's not working in Android 2.1.2.

**Comment by sfyc23** [comment]
me too

**Comment by Krishan14sharma** [comment]
same here

**Comment by ShkurtiA** [comment]
`com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:100)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:93)
    at com.intellij.ide.projectView.impl.ProjectAbstractTreeStructureBase.getProviders(ProjectAbstractTreeStructureBase.java:37)
    at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getProvidersDumbAware(AbstractTreeStructureBase.java:117)
    at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:48)
    at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1624)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1621)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$4700(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1546)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1533)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1259)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$3100(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1182)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1179)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1174)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1080)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
    at com.intellij.ide.util.treeView.AbstractTreeUi$13.perform(AbstractTreeUi.java:510)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doExpandNodeChildren(AbstractTreeUi.java:506)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.expandNodeChildren(AbstractTreeBuilder.java:355)
    at com.intellij.ide.projectView.BaseProjectTreeBuilder.expandNodeChildren(BaseProjectTreeBuilder.java:118)
    at com.intellij.ide.util.treeView.AbstractTreeUi$MyExpansionListener.treeExpanded(AbstractTreeUi.java:4817)
    at javax.swing.JTree.fireTreeExpanded(JTree.java:2666)
    at javax.swing.JTree.setExpandedState(JTree.java:3427)
    at javax.swing.JTree.expandPath(JTree.java:2163)
    at com.intellij.ide.util.treeView.AbstractTreeUi$56.perform(AbstractTreeUi.java:3273)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:123)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3294)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandPath(AbstractTreeUi.java:3262)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1492)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1480)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2000(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$16.perform(AbstractTreeUi.java:735)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.initRootNodeNowIfNeeded(AbstractTreeUi.java:771)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1062)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$2.run(AbstractTreeUpdater.java:215)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
    at com.intellij.util.ui.update.MergingUpdateQueue.showNotify(MergingUpdateQueue.java:211)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.showNotify(AbstractTreeUpdater.java:357)
    at com.intellij.ide.util.treeView.AbstractTreeUi.activate(AbstractTreeUi.java:403)
    at com.intellij.ide.util.treeView.AbstractTreeUi.initRootNode(AbstractTreeUi.java:668)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.initRootNode(AbstractTreeBuilder.java:272)
    at com.intellij.ide.projectView.impl.ProjectTreeBuilder.<init>(ProjectTreeBuilder.java:82)
    at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane$5.<init>(AbstractProjectViewPSIPane.java:204)
    at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane.createBuilder(AbstractProjectViewPSIPane.java:204)
    at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane.createComponent(AbstractProjectViewPSIPane.java:75)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.showPane(ProjectViewImpl.java:500)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.viewSelectionChanged(ProjectViewImpl.java:621)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.setupImpl(ProjectViewImpl.java:587)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.setupImpl(ProjectViewImpl.java:548)
    at com.intellij.ide.projectView.impl.ProjectViewToolWindowFactory.createToolWindowContent(ProjectViewToolWindowFactory.java:34)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:521)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$12.run(ToolWindowManagerImpl.java:559)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.diagnostic.PluginException: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:157)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
    ... 104 more
Caused by: java.lang.UnsupportedClassVersionError: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 112 more
Caused by:

com.intellij.diagnostic.PluginException: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:157)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:100)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:93)
    at com.intellij.ide.projectView.impl.ProjectAbstractTreeStructureBase.getProviders(ProjectAbstractTreeStructureBase.java:37)
    at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getProvidersDumbAware(AbstractTreeStructureBase.java:117)
    at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:48)
    at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1624)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1621)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$4700(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1546)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1533)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1259)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$3100(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1182)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1179)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1174)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1080)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
    at com.intellij.ide.util.treeView.AbstractTreeUi$13.perform(AbstractTreeUi.java:510)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doExpandNodeChildren(AbstractTreeUi.java:506)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.expandNodeChildren(AbstractTreeBuilder.java:355)
    at com.intellij.ide.projectView.BaseProjectTreeBuilder.expandNodeChildren(BaseProjectTreeBuilder.java:118)
    at com.intellij.ide.util.treeView.AbstractTreeUi$MyExpansionListener.treeExpanded(AbstractTreeUi.java:4817)
    at javax.swing.JTree.fireTreeExpanded(JTree.java:2666)
    at javax.swing.JTree.setExpandedState(JTree.java:3427)
    at javax.swing.JTree.expandPath(JTree.java:2163)
    at com.intellij.ide.util.treeView.AbstractTreeUi$56.perform(AbstractTreeUi.java:3273)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:123)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3294)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandPath(AbstractTreeUi.java:3262)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1492)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1480)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2000(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$16.perform(AbstractTreeUi.java:735)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.initRootNodeNowIfNeeded(AbstractTreeUi.java:771)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1062)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$2.run(AbstractTreeUpdater.java:215)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
    at com.intellij.util.ui.update.MergingUpdateQueue.showNotify(MergingUpdateQueue.java:211)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.showNotify(AbstractTreeUpdater.java:357)
    at com.intellij.ide.util.treeView.AbstractTreeUi.activate(AbstractTreeUi.java:403)
    at com.intellij.ide.util.treeView.AbstractTreeUi.initRootNode(AbstractTreeUi.java:668)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.initRootNode(AbstractTreeBuilder.java:272)
    at com.intellij.ide.projectView.impl.ProjectTreeBuilder.<init>(ProjectTreeBuilder.java:82)
    at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane$5.<init>(AbstractProjectViewPSIPane.java:204)
    at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane.createBuilder(AbstractProjectViewPSIPane.java:204)
    at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane.createComponent(AbstractProjectViewPSIPane.java:75)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.showPane(ProjectViewImpl.java:500)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.viewSelectionChanged(ProjectViewImpl.java:621)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.setupImpl(ProjectViewImpl.java:587)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.setupImpl(ProjectViewImpl.java:548)
    at com.intellij.ide.projectView.impl.ProjectViewToolWindowFactory.createToolWindowContent(ProjectViewToolWindowFactory.java:34)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:521)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$12.run(ToolWindowManagerImpl.java:559)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 112 more
`

**Comment by 949886** [comment]
same

**Comment by Krishan14sharma** [comment]
I finally made it work. Download the plugin from here [folding-plugin](https://github.com/dmytrodanylyk/folding-plugin/releases/download/v1.1.1/Android.File.Grouping.v1.1.1.zip)

**Comment by ShkurtiA** [comment]
still happening at me with AA 2.1.2 :

```
com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]

cannot create class "com.dd.ComposeAction" [Plugin: com.dmytrodanylyk.fold]
```

**Comment by Krishan14sharma** [comment]
I am on 2.2 beta and its working.

**Comment by jaumard** [comment]
Not working on mac and Android Studio 2.2.2 :( 
```
Build #AI-145.3360264, built on October 18, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
But very useful plugin !

**Comment by jaumard** [comment]
Ho ok, sorry my mistake it's working correctly but only for "Project" Tab not the "Android" tab. This issue is related https://github.com/dmytrodanylyk/folding-plugin/issues/17
