### ISSUE TITLE
Not working for me...

### ISSUE THREAD

**Issue by szuae** [dmytrodanylyk/folding-plugin#5]
I am trying to implement this on Android Studio 1.3 but not working for me.
Please advise

**Comment by Rainer-Lang** [comment]
I'm using also 1.3 and the plugin is working fine.

**Comment by szuae** [comment]
I have install your plugin successfully but unable to see group option when I do right click

**Comment by Rainer-Lang** [comment]
Under "project" view? 
"android" view isn't working.

**Comment by szuae** [comment]
yes I am doing same.
short cut is ALT + 1 correct...

**Comment by szuae** [comment]
I am getting this exception

class with name "com.dd.ComposeAction" not found [Plugin: com.dmytrodanylyk.fold]
com.intellij.diagnostic.PluginException: class with name "com.dd.ComposeAction" not found [Plugin: com.dmytrodanylyk.fold]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:516)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:496)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1310)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1303)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1303)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1297)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doPreloadActions(ActionManagerImpl.java:1287)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:76)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1268)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.ClassNotFoundException: com.dd.ComposeAction PluginClassLoader[com.dmytrodanylyk.fold, 1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 20 more

**Comment by szuae** [comment]
Correction:
It is working if I download it from the path you have mention in your installation steps, but fails if I download it from GIT.

**Comment by Rainer-Lang** [comment]
Sorry - now I couldn't help you.

**Comment by vitovalov** [comment]
Getting ` PicoPluginExtensionInitializationException: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]` at Android Studio 1.4.1 start. "Group" menu entry not appears.

**Comment by vitovalov** [comment]
Then even more exceptions are thrown:

`EmptyThrowable: Null child action in group Project View Popup Menu () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ComposeAction
`

**Comment by skyrylyuk** [comment]
I try reproduce it issue on stable release android-studio-ide-141.2343393 - can't reproduce. Please check - it issue is actual or not

**Comment by furedal** [comment]
Getting the same error as @vitovalov when trying this out on my Android studio 1.4.1. Group doesn't appear for me either.

**Comment by ZhaoKaiQiang** [comment]
not work for me too, with the following exception info

```
20:51:24 EmptyThrowable: Null child action in group Project View Popup Menu () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ComposeAction
```

**Comment by ZhaoKaiQiang** [comment]
And my Android Studio Version is 1.5

**Comment by lrchao** [comment]
And my Android Studio Version is 1.5 beta

**Comment by sh11mo** [comment]
My android studio version is 1.5.
[v1.0](https://github.com/dmytrodanylyk/folding-plugin/releases/tag/v1.0) Working.
[v1.1](https://github.com/dmytrodanylyk/folding-plugin/releases/tag/v1.1) Not working 
[v1.1.1](https://github.com/dmytrodanylyk/folding-plugin/releases/tag/v1.1.1) Not working.

**Comment by FtheGFW** [comment]
can't work with AS 1.5 STABLE

**Comment by futabooo** [comment]
not work for me too.
AndroidStudio version 2.0 Preview

```
2:28:04 Plugin Error: Android File Grouping threw an uncaught PluginException. Disable Plugin
2:28:04 PluginException: com/dd/SettingConfigurable : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
2:28:19 EmptyThrowable: Null child action in group Project View Popup Menu () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ComposeAction
```

**Comment by jemshit** [comment]
v1.5.1 on mac not working:

```
5:20:07 PicoPluginExtensionInitializationException: com/dd/ProjectStructureProvider : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
15:20:11 EmptyThrowable: Null child action in group Project View Popup Menu () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ComposeAction
```

**Comment by vuhung3990** [comment]
it only work on Project tab (don't select Android, Project Files....)

**Comment by itzikBraun** [comment]
I compiled the project with Java 6 and it seems to work with Android Studio1.5. 
First I compiled the project with Java 7 and got the above exceptions so I think making a new release with Java 6 would solve it.

**Comment by amatkivskiy** [comment]
Hi all, I've got this error on Android Studio 

Version: 

![screenshot 2016-02-09 11 37 00](https://cloud.githubusercontent.com/assets/3864884/12912471/78296c60-cf21-11e5-89c7-6ca4f00b7062.png)

Stacktrace: 

```
cannot create class "com.dd.ComposeAction" [Plugin: com.dmytrodanylyk.fold]
com.intellij.diagnostic.PluginException: cannot create class "com.dd.ComposeAction" [Plugin: com.dmytrodanylyk.fold]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:177)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:515)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:495)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:488)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1315)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1308)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1308)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1302)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doPreloadActions(ActionManagerImpl.java:1292)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:77)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1278)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.intellij.diagnostic.PluginException: com/dd/ComposeAction : Unsupported major.minor version 51.0 [Plugin: com.dmytrodanylyk.fold]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
    ... 21 more
Caused by: java.lang.UnsupportedClassVersionError: com/dd/ComposeAction : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 27 more

```

**Comment by manjunathc23** [comment]
+1

**Comment by jinzw1993** [comment]
Ubuntu 14 Android Studio2.1 java 1.8   I do not use。

**Comment by kongnanlive** [comment]
+1

**Comment by ashish-patidar-rau** [comment]
I am using 
`Android Studio 3.4.2
Build #AI-183.6156.11.34.5692245, built on June 27, 2019
JRE: 1.8.0_152-release-1343-b16-5323222 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-50-generic`

**1. It is working in Project View
2. but not working in Android View**
